### ISSUE TITLE
How to compile tool on Ubuntu 20.04?

### ISSUE THREAD

**Issue by markwomack** [GridProtectionAlliance/udp2serial#1]
I'm sorry if this is a noob question...but how do I compile this on Ubuntu 20.04? I dug around on the interwebs, and I installed the mono-complete package, but I can't seem to figure out what file to actually compile. Some kind of file to point noobs in the right direction would be super helpful.

**Comment by ritchiecarroll** [comment]
This is a .NET core application - so it should readily compile on Ubuntu without needing Mono. Just install .NET (core), e.g., version 5.0 or 6.0, on your Ubuntu system then compile using `dotnet build` in the folder with the solution / project files.

That said, the Linux releases ([here](https://github.com/GridProtectionAlliance/udp2serial/releases)) should be good to go if you just want to use the app...

Good luck!

Thanks,
Ritchie

**Comment by markwomack** [comment]
Ah, this precompiled binary is more my speed. Thanks!

**Comment by markwomack** [comment]
Sorry, I spoke too soon. I installed both the .NET sdk and runtime 6.0 on Ubuntu 20.04. .NET seems to be happy. But I still can't figure out the magic incantation. I tried making it an executable, I tried dotnet run. Sorry I am a noob on this.

**Comment by ritchiecarroll** [comment]
Let's try these steps:

```sh
# Download Linux release (may need to "sudo apt install wget" to install wget)
wget https://github.com/GridProtectionAlliance/udp2serial/releases/download/v1.2/linux-x64.zip
# Make a directory to hold exe
mkdir udp2serial
# Unzip Linux release (may need to "sudo apt install unzip" to install unzip)
unzip linux-x64.zip -d udp2serial
# Mark program as executable
chmod u+x udp2serial/udp2serial
# Run program (in this example, listen on UDP port 9500 and forward data to serial device /dev/ttyS0)
sudo udp2serial/udp2serial 9500 /dev/ttyS0
```

**Comment by ritchiecarroll** [comment]
BTW - you don't need to install .NET just to run the pre-compiled executable
